var vocabulary = {"abbiegen":"turn","Abend":"evening","Abendessen":"dinner","Abenteuer":"adventure","aber":"but","Abfall":"waste","Abhang":"slope",
"abkuehlen":"cool","ablehnen":"refuse","Ablehnung":"refusal","Abmachung":"arrangement","Abnutzung":"wear","Abrechnung":"account","Abreise":"departure","abreisen":"start",
"Alter":"age","Amerika":"America","amerikanisch":"American","Amt":"office","anbieten":"offer","Anblick":"sight",
"anderenfalls":"otherwise","anderer":"other","aenderung":"change","Anfang":"start","anfangen":"start",
"Angebot":"offer","angeliefert":"delivered","Arbeitgeber":"employer","Arbeitnehmer":"employee","arbeitslos":"unemployed",
"Argument":"argument","Arm":"arm","arm":"poor","aermel":"sleeve","Armut":"poverty","nun":"now","nun ja":"well","nur":"only","nutzen":"use","Nutzen":"use",
"Bekleidung":"clothing","bekommen":"got","beleidigen":"offend","Beleidigung":"offence","Beleuchtung":"lighting","Belgien":"Belgium","beliebt":"popular","berechnend":"calculating",
"berechnet":"calculated","Berechnung":"calculation","bereit":"ready","Berg":"mountain","Braut":"bride","Bräutigam":"bridegroom","breit":"wide","Breite":"width","breitete aus":"spread","Diebe":"thieves",
"dienen":"serve","Diener":"servant","Dienst":"service","Dienstag":"Tuesday","ehrlich":"honest","Ei":"egg","Eiche":"oak","eiferssüchtig":"jealous","Eifersucht":"jealousy","eifrig":"keen","Eigenart":"peculiarity",
"Eigenschaft":"quality","Eigentum":"property","Erfrischung":"refreshment","ergeben":"yield","Ergebnis":"result","ergreifen":"seize","erhalten":"receive","fett":"fat","Fett":"grease","fleckenlos":"spotless","Fleisch":"meat",
"harmlos":"harmless","hart":"hard","Härte":"hardship","harte Umstände":"hardship","härten":"harden","Hass":"hate"}