var data = [
    "Car",
    "Spoon",
    "Never","Able","About","Above", "Across", "Act", "Actor", "Active", "Activity", "Add", "Afraid","After", 
    "Again", "Age", "Agree", "Air",  "Alone", "Already", "Always", "Amount","Angry", "Animal", 
    "Another", "Answer",  "Anyone", "Anything", "Anytime", "Appear", "Apple","Area", "Arm", "Army", "Around", 
    "Arrive","Art","Attack", "Aunt", "Autumn", "Away","Baby", "Base", "Back","Bag","Ball", "Bank", "Basket", 
    "Bath","Bean", "Bear", "Beautiful", "Beer", "Bed", "Bedroom", "Behave", "Before", "Begin", "Behind", 
    "Bell", "Below", "Besides", "Best", "Better", "Between", "Big", "Bird", "Birth", "Birthday", "Bite", 
    "Black","Bleed", "Block", "Blood",
    "Cake","Call","Can", "Candle", "Cap", "Car", "Card", "Care", "Careful", "Careless", "Case", "Cat", "Catch",
    "Chair","Cheap", "Cheese", "Chicken", "Child","Chocolate","Circle", "City", "Class", "Clever", "Clean", "Clear", 
    "Climb", "Clock", "Cloth", "Clothes", "Cloud","Coffee", "Coat", "Coin", "Cold", "Collect","Comb", 
    "Comfortable","Compare", "Complete", "Computer", "Condition","Control", "Cook", "Cool", "Copper", "Corn", 
    "Corner", "Correct", "Cost", "Course", "Cover", "Crash", "Cross", "Cry", "Cup", "Cupboard", "Cut",
    "Dance", "Danger","Dark", "Daughter", "Day", "Dead","Deep", "Deer", "Desk", "Destroy", 
    "Develop","Different", "Difficult", "Dinner", "Direction", "Dirty", "Discover", "Dish","Dog", "Door",
    "Dream", "Dress","Drop", "Dry", "Duck", "Dust", "Duty",
    "Ear","Earth", "East", "Easy", "Eat", "Education", "Effect", "Egg", "Eight", "Either", "Electric", 
    "Elephant", "Else", "Empty", "End", "Enemy", "Enjoy", "Enough", "Enter", "Equal", "Entrance",
    "Example", "Except", "Excited", "Exercise","Expensive", "Explain", "Extremely", "Eye",
    "Face", "Fact","Fall", "False", "Family", "Famous", "Far", "Farm", "Father", "Fast", "Fat", "Fault", "Fear", 
    "Feed", "Feel", "Female", "Fever", "Few", "Fight", "Fill", "Film", "Find","Finger", "Finish", "Fire", 
    "First", "Fit", "Five", "Fix"," flag", "Flat",
    "Game", "Garden", "Gate", "General", "Gentleman","Gift","Glass", "Go", "Goat", "God", "Gold", "Good", "Goodbye",
    "Hair","Half","Hall","Hammer","Hand","Happen","Happy","Hard","Hat","Hate","Have","Head","Healthy",
    "Hear","Heavy","Hello","Help","Heart","Heaven","Height","Hen","Hide","High","Hill","Hit","Hobby",
    "Ice", "Idea","Important", "Increase", "Inside", "Introduce", "Invent", "Iron", "Invite", "Island",
    "Job", "Join", "Juice", "Jump","Keep", "Key", "Kid", "Kill", "Kind", "King", "Kitchen", "Knee", 
    "Knife", "Knock", "Know",
    "Ladder", "Lady", "Lamp", "Land", "Large", "Last", "Late","Lazy","Leaf", "Learn", "Leave", 
    "Leg", "Left", "Length", "Lesson", "Letter", "Library", "Lie", "Life", "Light","Lion",
    "Machine", "Map", "Mark", "Market", "Marry", "Matter","Meal", "Mean", 
    "Measure", "Meat", "Medicine", "Meet", "Member", "Mention", "Method", "Middle", "Milk",
    "Name", "Narrow", "Nation", "Nature", "Near", "Nearly", "Neck", "Need", "Needle", "Neighbour", "Neither", 
    "Net", "Never", "New", "News", "Newspaper", "Next", "Nice", "Night",
    "Obey", "Object", "Ocean", "Offer", "Office", "Often", "Oil", "Old", "Only", "Open", "Opposite",
    "Power", "Present", "Press", "Pretty", "Prevent", "Price", "Prince", "Prison", "Private", "Prize", 
    "Probably", "Problem", "Produce", "Promise", "Queen", "Question", "Quick", "Quiet", "Quite",
    "Radio", "Rain", "Read", "Ready", "Real", "Really", "Receive", "Record", "Red", "Remember", "Remind", "Remove", "Rent", "Repair", "Repeat",
    "Year", "Yellow", "Yesterday", "Table", "Take", "Talk", "Tall", "Taste", "Taxi", "Tea", "Teach", "Team", "Tear", "Telephone"
]

