var data = [
    "car",
    "spoon",
    "never","able","about","above", "across", "act", "actor", "active", "activity", "add", "afraid","after", 
    "again", "age", "agree", "air",  "alone", "already", "always", "amount","angry", "animal", 
    "another", "answer",  "anyone", "anything", "anytime", "appear", "apple","area", "arm", "army", "around", 
    "arrive","art","attack", "aunt", "autumn", "away","baby", "base", "back","bag","ball", "bank", "basket", 
    "bath","bean", "bear", "beautiful", "beer", "bed", "bedroom", "behave", "before", "begin", "behind", 
    "bell", "below", "besides", "best", "better", "between", "big", "bird", "birth", "birthday", "bite", 
    "black","bleed", "block", "blood",
    "cake","call","can", "candle", "cap", "car", "card", "care", "careful", "careless", "case", "cat", "catch",
    "chair","cheap", "cheese", "chicken", "child","chocolate","circle", "city", "class", "clever", "clean", "clear", 
    "climb", "clock", "cloth", "clothes", "cloud","coffee", "coat", "coin", "cold", "collect","comb", 
    "comfortable","compare", "complete", "computer", "condition","control", "cook", "cool", "copper", "corn", 
    "corner", "correct", "cost", "course", "cover", "crash", "cross", "cry", "cup", "cupboard", "cut",
    "dance", "danger","dark", "daughter", "day", "dead","deep", "deer", "desk", "destroy", 
    "develop","different", "difficult", "dinner", "direction", "dirty", "discover", "dish","dog", "door",
    "dream", "dress","drop", "dry", "duck", "dust", "duty",
    "ear","earth", "east", "easy", "eat", "education", "effect", "egg", "eight", "either", "electric", 
    "elephant", "else", "empty", "end", "enemy", "enjoy", "enough", "enter", "equal", "entrance",
    "example", "except", "excited", "exercise","expensive", "explain", "extremely", "eye",
    "face", "fact","fall", "false", "family", "famous", "far", "farm", "father", "fast", "fat", "fault", "fear", 
    "feed", "feel", "female", "fever", "few", "fight", "fill", "film", "find","finger", "finish", "fire", 
    "first", "fit", "five", "fix","flag", "flat",
    "game", "garden", "gate", "general", "gentleman","gift","glass", "go", "goat", "god", "gold", "good", "goodbye",
    "hair","half","hall","hammer","hand","happen","happy","hard","hat","hate","have","head","healthy",
    "hear","heavy","hello","help","heart","heaven","height","hen","hide","high","hill","hit","hobby",
    "ice", "idea","important", "increase", "inside", "introduce", "invent", "iron", "invite", "island",
    "job", "join", "juice", "jump","keep", "key", "kid", "kill", "kind", "king", "kitchen", "knee", 
    "knife", "knock", "know",
    "ladder", "lady", "lamp", "land", "large", "last", "late","lazy","leaf", "learn", "leave", 
    "leg", "left", "length", "lesson", "letter", "library", "lie", "life", "light","lion",
    "machine", "map", "mark", "market", "marry", "matter","meal", "mean", 
    "measure", "meat", "medicine", "meet", "member", "mention", "method", "middle", "milk",
    "name", "narrow", "nation", "nature", "near", "nearly", "neck", "need", "needle", "neighbour", "neither", 
    "net", "never", "new", "news", "newspaper", "next", "nice", "night",
    "obey", "object", "ocean", "offer", "office", "often", "oil", "old", "only", "open", "opposite",
    "power", "present", "press", "pretty", "prevent", "price", "prince", "prison", "private", "prize", 
    "probably", "problem", "produce", "promise", "queen", "question", "quick", "quiet", "quite",
    "radio", "rain", "read", "ready", "real", "really", "receive", "record", "red", "remember", "remind", "remove", "rent", "repair", "repeat",
    "year", "yellow", "yesterday", "table", "take", "talk", "tall", "taste", "taxi", "tea", "teach", "team", "tear", "telephone"
]

